# Generated by Django 4.2.2 on 2023-07-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="logo",
            field=models.ImageField(
                default="images/default_logo.png", upload_to="images/course_logos"
            ),
        ),
    ]
