# Generated by Django 4.2.2 on 2023-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="profile_pics/default.jpg", upload_to="profile_pics"
            ),
        ),
    ]
