# Generated by Django 4.2.2 on 2023-06-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="profile_pic", new_name="profile_pics",
        ),
    ]
